#include "check_mqtt.h"
#include "usage.h"

#include <stdio.h>

void usage(void) {
    fprintf(stdout, "check_mqtt version %s\n"
            "Copyright (C) by Andreas Maus <maus@ypbind.de>\n"
            "This program comes with ABSOLUTELY NO WARRANTY.\n"
            "\n"
            "check_mqtt is distributed under the terms of the GNU General\n"
            "Public License Version 3. (http://www.gnu.org/copyleft/gpl.html)\n"
            "\n"
            "Usage: check_mqtt [-h|--help] -H <host>|--host=<host> [-p <port>|--port=<port>] \n"
            "   [-c <cert>|--cert=<cert>] [-k <key>|--key=<key>] [-C <ca>|--ca=<ca>]\n"
            "   [-D <dir>|--cadir=<dir>] [-i|--insecure] [-Q <qos>|--qos=<qos>]\n"
            "   [-T <topic>|--topic=<topic>] [-t <sec> | --timeout=<sec>] [-s|--ssl]\n"
            "   [-u <user>|--user=<user>] [-P <pass>|--password=<pass>] \n"
            "   [-f <file>|--password-file=<file>] [-w <ms>|--warn=<ms>] \n"
            "   [-W <ms>|--critical=<ms>] [-K <s>|--keepalive=<s>]\n"
            "\n"
            "   -h                      This text\n"
            "   --help\n"
            "\n"
            "   -H <host>               Connect to <host>\n"
            "   --host=<host>           This option is mandatory\n"
            "\n"
            "   -p <port>               Connect to <port>\n"
            "   --port=<port>           Default: %u\n"
            "\n"
            "   -c <cert>               Use certificate for authentication with SSL\n"
            "   --cert=<cert>           client certificate\n"
            "\n"
            "   -k <key>                Use private key for authentication with SSL\n"
            "   --key=<key>             client certificate\n"
            "\n"
            "   -C <ca>                 Use <ca> as CA file for server certificate\n"
            "   --ca=<ca>\n"
            "\n"
            "   -D <dir>                Use <dir> as directory containing CA certificates\n"
            "   --cadir=<dir>           Default: %s\n"
            "\n"
            "   -i                      Don't verify SSL certificate of the server\n"
            "   --insecure\n"
            "\n"
            "   -Q <qos>                QoS to use for message\n"
            "   --qos=<qos>             Default: %u\n"
            "\n"
            "   -T <topic>              Topic to send probe message to\n"
            "   --topic=<topic>         Default: %s\n"
            "\n"
            "   -t <sec>                Timeout in seconds for connection and arrival of probe message\n"
            "   --timeout=<sec>         Default: %u\n"
            "\n"
            "   -s                      Use SSL\n"
            "   --ssl\n"
            "\n"
            "   -u <user>               Authenticate with <user>/<password> instead of SSL client\n"
            "   --user=<user>           certificate\n"
            "\n"
            "   -P <pass>               Authenticate with <user>/<password> instead of SSL client\n"
            "   --password=<pass>       certificate\n"
            "\n"
            "   -f <file>               Read password from <file>. Password is expected to be on the\n"
            "   --password-file=<file>  first line of the file\n"
            "\n"
            "   -w <ms>                 Warn if probe message arrives <ms> milliseconds or later\n"
            "   --warn=<ms>             Default: %u\n"
            "\n"
            "   -W <ms>                 Critical if probe message arrives <ms> milliseconds or later\n"
            "   --critical=<ms>         Default: %u\n"
            "\n"
            "   -K <s>                  Send MQTT PING message after <s> if no messages are exchanged\n"
            "   --keapalive=<s>         Default: %d\n"
            "\n", CHECK_MQTT_VERSION, DEFAULT_PORT, DEFAULT_CADIR, DEFAULT_QOS, DEFAULT_TOPIC, DEFAULT_TIMEOUT, DEFAULT_WARN_MS, DEFAULT_CRITICAL_MS, DEFAULT_KEEP_ALIVE);
}

