#include "check_mqtt.h"
#include "usage.h"

#include <stdio.h>

void usage(void) {
    fprintf(stdout, "check_mqtt version %s\n"
            "Copyright (C) by Andreas Maus <maus@ypbind.de>\n"
            "This program comes with ABSOLUTELY NO WARRANTY.\n"
            "\n"
            "check_mqtt is distributed under the terms of the GNU General\n"
            "Public License Version 3. (http://www.gnu.org/copyleft/gpl.html)\n"
            "\n"
            "Usage: check_mqtt --help --host=<host> -port=<port> --cert=<cert> \n"
            "   --key=<key> --ca=<ca> --insecure --qos=<qos> --topic=<topic> \n"
            "   --timeout=<sec> --ssl --user=<user> --password=<pass> --warn=<ms> \n"
            "   --critical=<ms> --keepalive=<s>\n"
            "\n"
            "   --help              This text\n"
            "\n"
            "   --host=<host>       Connect to <host>\n"
            "                       This option is mandatory\n"
            "\n"
            "   --port=<port>       Connect to <port>\n"
            "                       Default: %u\n"
            "\n"
            "   --cert=<cert>       Use certificate for authentication with SSL\n"
            "                       client certificate\n"
            "\n"
            "   --key=<key>         Use private key for authentication with SSL\n"
            "                       client certificate\n"
            "\n"
            "   --ca=<ca>           Use <ca> as CA file for server certificate\n"
            "\n"
            "   --insecure          Don't verify SSL certificate of the server\n"
            "\n"
            "   --qos=<qos>         QoS to use for message\n"
            "                       Default: %u\n"
            "\n"
            "   --topic=<topic>     Topic to send probe message to\n"
            "                       Default: %s\n"
            "\n"
            "   --timeout=<sec>     Timeout in seconds for connection and arrival of probe message\n"
            "                       Default: %u\n"
            "\n"
            "   --ssl               Use SSL\n"
            "\n"
            "   --user=<user>       Authenticate with <user>/<password> instead of SSL client\n"
            "                       certificate\n"
            "\n"
            "   --password=<pass>   Authenticate with <user>/<password> instead of SSL client\n"
            "                       certificate\n"
            "\n"
            "   --warn=<ms>         Warn if probe message arrives <ms> milliseconds or later\n"
            "                       Default: %u\n"
            "\n"
            "   --critical=<ms>     Critical if probe message arrives <ms> milliseconds or later\n"
            "                       Default: %u\n"
            "\n"
            "   --keepalive=<s>     Send MQTT PING message after <s> if no messages are exchanged\n"
            "                       Default: %d\n"
            "\n", CHECK_MQTT_VERSION, DEFAULT_PORT, DEFAULT_QOS, DEFAULT_TOPIC, DEFAULT_TIMEOUT, DEFAULT_WARN_MS, DEFAULT_CRITICAL_MS, DEFAULT_KEEP_ALIVE);
}

